# Generated by Django 3.2.9 on 2023-12-14 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'verbose_name': '订单项详情', 'verbose_name_plural': '订单项详情'},
        ),
    ]
