# Generated by Django 3.2.9 on 2023-12-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderdetail_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='credit',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='积分'),
        ),
    ]
