# Generated by Django 3.2.9 on 2023-12-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='attachment_link',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='课件链接'),
        ),
        migrations.AlterField(
            model_name='course',
            name='attachment_path',
            field=models.FileField(blank=True, max_length=128, null=True, upload_to='', verbose_name='课件路径'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_cover',
            field=models.ImageField(blank=True, max_length=128, null=True, upload_to='course/cover', verbose_name='封面图片'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_video',
            field=models.FileField(blank=True, max_length=128, null=True, upload_to='course/video', verbose_name='封面视频'),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='分类名称'),
        ),
        migrations.AlterField(
            model_name='coursedirection',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='方向名称'),
        ),
        migrations.AlterField(
            model_name='courselesson',
            name='duration',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='课时时长'),
        ),
        migrations.AlterField(
            model_name='courselesson',
            name='lesson_link',
            field=models.CharField(blank=True, help_text='若是video，填视频地址或者视频id，若是文档，填文档地址', max_length=128, null=True, verbose_name='课时链接'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='brief',
            field=models.TextField(max_length=128, verbose_name='讲师描述'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='signature',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='导师签名'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='title',
            field=models.CharField(max_length=128, verbose_name='职位、职称'),
        ),
    ]
