# Generated by Django 3.2.9 on 2023-12-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20231213_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.SmallIntegerField(choices=[(0, '实战课程'), (1, '会员专享'), (2, '学位课程')], default=0, verbose_name='付费类型'),
        ),
    ]
